0,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_has_no_cause
8,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_has_no_cause
9,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_has_no_cause
10,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_has_no_cause
0,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_is_null
8,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_is_null
9,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_is_null
10,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_actual_is_null
0,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
1,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
2,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
3,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
4,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
5,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
6,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
7,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
0,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
1,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
2,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
3,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
4,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
5,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
6,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
7,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_pass_if_cause_is_exactly_instance_of_expected_type
0,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
1,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
2,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
3,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
4,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
5,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
6,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
7,org.assertj.core.internal.throwables.Throwables_assertHasCauseExactlyInstanceOf_Test:should_fail_if_cause_is_not_exactly_instance_of_expected_type
0,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
1,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
2,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
3,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
4,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
5,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
6,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
7,org.assertj.core.api.optionalint.OptionalIntAssert_isNotPresent_Test:should_fail_if_OptionalInt_is_present
