9,org.assertj.core.internal.throwables.Throwables_assertHasCauseInstanceOf_Test:should_fail_if_actual_has_no_cause
10,org.assertj.core.internal.throwables.Throwables_assertHasCauseInstanceOf_Test:should_fail_if_actual_has_no_cause
2,org.assertj.core.internal.throwables.Throwables_assertHasCauseInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
3,org.assertj.core.internal.throwables.Throwables_assertHasCauseInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
4,org.assertj.core.internal.throwables.Throwables_assertHasCauseInstanceOf_Test:should_fail_if_cause_is_not_instance_of_expected_type
